#!/usr/bin/env bash

### ANSI escape colour codes
blue="\u001b[36m"
reset_colour="\u001b[0m"

### Sources
source ./sources/disks.sh
source ./sources/displays.sh
source ./sources/locale.sh
source ./sources/memory.sh
source ./sources/packages.sh
source ./sources/quick_queries.sh
source ./sources/uptime.sh
source ./sources/window_manager.sh

### Logo
arch_logo=(
    '                  -`'
    '                 .o+`'
    '                `ooo/'
    '               `+oooo:'
    '              `+oooooo:'
    '              -+oooooo+:'
    '            `/:-:++oooo+:'
    '           `/++++/+++++++:'
    '          `/++++++++++++++:'
    '         `/+++ooooooooooooo/`'
    '        ./ooosssso++osssssso+`'
    '       .oossssso-````/ossssss+`'
    '      -osssssso.      :ssssssso.'
    '     :osssssss/        osssso+++.'
    '    /ossssssss/        +ssssooo/-'
    '  `/ossssso+/:-        -:/+osssso+-'
    ' `+sso+:-`                `.-/+oso:'
    '`++:.                           `-/+/'
    '.`                                 `/'
)





### Output information
output=()

output+=("${blue}$USER${reset_colour}@${blue}$HOSTNAME${reset_colour}")
output+=("------------------")
output+=("${blue}OS:${reset_colour} $os_version")
output+=("${blue}Kernel:${reset_colour} $kernel_version")
output+=("${blue}Bootloader:${reset_colour} $boot_manager")

# Display output for all active monitors
for i in "${!monitor_names[@]}"
do
    monitor_current_name="${monitor_names[$i]}"
    monitor_current_resolution="${monitor_resolutions[$i]}"

    output+=("${blue}Display (${monitor_current_name}):${reset_colour} ${monitor_current_resolution}")
done

output+=("${blue}CPU:${reset_colour} ${cpu_model} (${cpu_amount}) @ ${cpu_speed_ghz} (${cpu_usage} %%)")
output+=("${blue}GPU:${reset_colour} ${gpu_manufacturer} ${gpu_model}")
output+=("${blue}Memory:${reset_colour} ${mem_used_gib} GiB / ${mem_total_gib} GiB (${mem_usage} %%)")
output+=("${blue}Swap:${reset_colour} ${swap_output}")
output+=("${blue}Disk (/):${reset_colour} ${disk_root_used_gib} GiB / ${disk_root_total_gib} GiB ($disk_root_usage %%)")

if [[ -n "$disk_home_output" ]]
then
    output+=("$disk_home_output")
fi

output+=("")

output+=("${blue}Uptime:${reset_colour} ${uptime_output}")
output+=("${blue}Packages:${reset_colour} ${packages_pacman} (pacman)${packages_flatpak_output}")
output+=("${blue}Shell:${reset_colour} ${shell}")
output+=("${blue}Window Manager:${reset_colour} ${wm_output}")
output+=("${blue}Locale:${reset_colour} ${locale_output}")

output+=("")

output+=("${blue}Local IP:${reset_colour} ${ip_local}")
output+=("${blue}Public IP:${reset_colour} ${ip_public}")





### Final Output
# Remove unnecessary Line Breaks
for i in "${!output[@]}"; do
    output[$i]="${output[$i]//\\n/}"
    output[$i]="${output[$i]//$'\n'/}"
done


# Calculate max height to prevent cutting of info and/or logo
logo_max_lines=${#arch_logo[@]}

if [[ ${#output[@]} -gt $logo_max_lines ]]
then
    logo_max_lines=${#output[@]}
fi


# Render output
for ((i=0; i<logo_max_lines; i++)); do

    if [[ $i -lt ${#arch_logo[@]} ]]
    then
        printf "${blue}%-38s${reset_colour}  " "${arch_logo[$i]}"
    else
        printf "%-38s  " "" 
    fi


    if [[ $i -lt ${#output[@]} ]]
    then
        printf "%b\n" "${output[$i]}"
    else
        printf "\n"
    fi
done